[[types]]
name = "feat"
summary = "New user facing functionality"
description = """
Commits of this type introduce new functionality.
This means that commit-lsp can offer more to the user.
It does not include purely internal code additions,
nor code hidden behind a feature flag (e.g. debug build).
"""

[[types]]
name = "fix"
summary = "A bugfix"
description = """
Commits of this type resolve bugs in existing code.
They are normally accompanied by a reference to an issue.
"""

[[types]]
name = "docs"
summary = "New or enhanced documentation"
description = """
Commits of this type extend or update documentation.
They generally don't change code.
"""

[[types]]
name = "refactor"
summary = "Internal code changes without direct user impact"
description = """
This type includes all code changes that don't have direct user impact.
For example adding a struct or module in preparation for a new feature.
If the impact of the code is hidden behind a disabled feature flag,
for example code that is only enabled in debug builds,
then it also counts as `refactor`.
"""

[[types]]
name = "chore"
summary = "General housekeeping in the project"
description = """
Changes to the project that do not touch code, but the tooling around it.
For example adjustments to the CI pipeline or
configurations for linters/formatters.
"""

[[types]]
name = "test"
summary = "New or fixed tests"
description = """
Changes to existing tests (e.g. unit or integration tests)
or implementation of new tests.
"""

[[scopes]]
name = "api"
summary = "Adjustments to the api"
description = """
This scope includes openapi changes or controller implementation.
"""

